files:
  - source: /package.nls.json
    translation: /package.nls.%two_letters_code%.%file_extension%
  - source: /locale/lang.en.json
    translation: /locale/lang.%two_letters_code%.%file_extension%
